// ---------- Timeouts (ms) ----------
const RECONNECT_DELAY_MS = 3000;
const SYNC_POLL_MS = 10000;
const ATTENTION_CHECK_MS = 30000;
const HEALTH_TIMEOUT_MS = 5000;
const SOCKET_TIMEOUT_MS = 10000;
const MIN_BILLABLE_MS = 60000;
const DAEMON_TIMEOUT_MS = 30000;
const DAEMON_SPAWN_TIMEOUT_MS = 15000;
const SCRIPT_TIMEOUT_MS = 60000;
const SERIAL_BAUD_TIMEOUT_MS = 5000;
const BT_HEALTH_INTERVAL_MS = 60000;
const BT_PNP_QUERY_TIMEOUT_MS = 10000;
const PROC_KILL_GRACE_MS = 2000;

// ---------- Retry / batching ----------
const SYNC_MAX_ATTEMPTS = 8;
const SYNC_BATCH_SIZE = 20;
const SYNC_SENT_RETENTION_DAYS = 30;
const SYNC_LOG_RETENTION_DAYS = 30;

// ---------- List limits ----------
const PENDING_DRAIN_LIMIT = 50;
const LOGS_DEFAULT_LIMIT = 100;

// ---------- Defaults ----------
const RECOVERY_GRACE_SEC_DEFAULT = '120';

module.exports = {
  RECONNECT_DELAY_MS,
  SYNC_POLL_MS,
  SYNC_MAX_ATTEMPTS,
  SYNC_BATCH_SIZE,
  SYNC_SENT_RETENTION_DAYS,
  SYNC_LOG_RETENTION_DAYS,
  ATTENTION_CHECK_MS,
  RECOVERY_GRACE_SEC_DEFAULT,
  HEALTH_TIMEOUT_MS,
  PENDING_DRAIN_LIMIT,
  LOGS_DEFAULT_LIMIT,
  SOCKET_TIMEOUT_MS,
  MIN_BILLABLE_MS,
  DAEMON_TIMEOUT_MS,
  DAEMON_SPAWN_TIMEOUT_MS,
  SCRIPT_TIMEOUT_MS,
  SERIAL_BAUD_TIMEOUT_MS,
  BT_HEALTH_INTERVAL_MS,
  BT_PNP_QUERY_TIMEOUT_MS,
  PROC_KILL_GRACE_MS,
};
